// var sections = [
//     {is_checked:false, value: 'a', is_active:false},
//     {is_checked:false, value: 'b', is_active:false},
//     {is_checked:false, value: 'c', is_active:false},
//     {is_checked:false, value: 'd', is_active:false},
//     {is_checked:false, value: 'e', is_active:false},
//     {is_checked:false, value: 'f', is_active:false},
//     {is_checked:false, value: 'g', is_active:false},
//     {is_checked:false, value: 'h', is_active:false},
//     {is_checked:false, value: 'i', is_active:false},
//     {is_checked:false, value: 'j', is_active:false},

// ];
export const ClassesList=[
    {id: 1, place:'st', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 2, place:'nd', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 3, place:'rd', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 4, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 5, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 6, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 7, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 8, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 9, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 10, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 11, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
    {id: 12, place:'th', is_selected:false, sections:[
        {is_checked:false, value: 'a', is_active:false},
        {is_checked:false, value: 'b', is_active:false},
        {is_checked:false, value: 'c', is_active:false},
        {is_checked:false, value: 'd', is_active:false},
        {is_checked:false, value: 'e', is_active:false},
        {is_checked:false, value: 'f', is_active:false},
        {is_checked:false, value: 'g', is_active:false},
        {is_checked:false, value: 'h', is_active:false},
        {is_checked:false, value: 'i', is_active:false},
        {is_checked:false, value: 'j', is_active:false},
        
    ]},
];